{% set name = "clease" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b62d838532b69abeed113f672a82157f42bd31d3a7bee0be0a2082821f16816

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - ase >=3.18
    - matplotlib
    - spglib
    - scikit-learn
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - clease

about:
  home: https://gitlab.com/computationalmaterials/clease
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: 'CLuster Expansion in Atomic Simulation Environment'

  description: |
    CLuster Expansion in Atomic Simulation Environment
  doc_url: https://gitlab.com/computationalmaterials/clease
  dev_url: https://gitlab.com/computationalmaterials/clease

extra:
  recipe-maintainers:
    - jan-janssen
