{% set name = "clease" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea53201bbd47c03eec86ffb008bfa2522f37e54649229eac0a3613c535e8facb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - pip
    - ase >=3.18
    - matplotlib-base
    - spglib
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - scipy
    - deprecated
    - mock
    - pytest
    - pytest-mock

test:
  imports:
    - clease
  commands:
    - pip check

about:
  home: https://computationalmaterials.gitlab.io/clease/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: CLuster Expansion in Atomic Simulation Environment

  description: |
    CLuster Expansion in Atomic Simulation Environment
  doc_url: https://computationalmaterials.gitlab.io/clease/
  dev_url: https://gitlab.com/computationalmaterials/clease

extra:
  recipe-maintainers:
    - jan-janssen
