{% set name = "clease" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05afbcc7bf189d9af0a063469b35b0386510f2118cbf5ea8b85076d4e2650c27

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]
  entry_points:
    - clease=clease.cli.main:clease_cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - pip
    - attrs
    - cython
    - ase >=3.20
    - matplotlib-base
    - spglib
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - scipy
    - deprecated
    - click >=8.0.0

test:
  imports:
    - clease
  commands:
    - pip check

about:
  home: https://clease.readthedocs.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: CLuster Expansion in Atomic Simulation Environment

  description: |
    CLuster Expansion in Atomic Simulation Environment
  doc_url: https://clease.readthedocs.io/
  dev_url: https://gitlab.com/computationalmaterials/clease

extra:
  recipe-maintainers:
    - jan-janssen
    - atygesen
